server:
  port: 8081

spring:
  application:
    name: Liquibase-app

  data:
    mongodb:
      uri: mongodb://localhost:27017/liquibase_db

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: mongodb://localhost:27017/liquibase_db
    driver: liquibase.ext.mongodb.database.MongoClientDriver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://test.retax.in/realms/SpringBoot

keycloak:
  admin:
    server-url: https://test.retax.in
    realm: master
    username: admin
    password: ${KEYCLOAK_ADMIN_PASSWORD:}
    client-id: admin-cli
    app-realm: SpringBoot

  client:
    id: springboot-client
    secret: SEXEbPP2t4GfWg59fWgrB5H9EDBUN7KX

springdoc:
  swagger-ui:
    path: /swagger-ui.html